config/routes.rb
Rails.application.routes.draw do
  
  

  resources :evaluations
  resources :sum_evaluations
  resources :projects
  #resources :cities
  #resources :states
  resources :user_startups
  resources :user_normals
  #resources :cargos
  resources :companypowers
  #resources :users
  get 'welcome/index'

 
  
=begin 

resources :user_normals do
match 'resetavaliacao' => 'user_normals#resetavaliacao', via: [:get, :post], as: :reset
#  collection {post :upload}
end  
=end 
devise_scope :users do
  get 'signin', to: 'users/sessions#new'
  #get 'signout', to: 'users/registration#destroy'
  get 'welcome/sobre', to: 'welcome#sobre', as: 'welcome/sobre' 
  get 'welcome/allpages', to: 'welcome#allpages', as: 'welcome/allpages'
  get 'users/accountaltsenha/:id', to: 'users#accountaltsenha', as: 'users/accountaltsenha'
  get 'user_normals/resetavaliacao/:id', to: 'user_normals#resetavaliacao', as: 'user_normals/resetavaliacao'  
end
  
  
resource :user, only: [:edit] do #Atenção rota para alterar a senha do usuário
  collection do
    patch 'update_password'
  end
end 

devise_for :users, controllers:{
  sessions: 'users/sessions'
 } 
  
resources :users  
root "welcome#index"  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
#If no route matches#
 match '*path', via: :all, to: redirect('/404')   
  
  

end

app/models/user_startup.rb
class UserStartup < ApplicationRecord
  belongs_to :user
#  belongs_to :cargo
#  belongs_to :city
#  belongs_to :state
  
  enum status: [ :'ativo', :'inativo'] 
  enum enquadramentoppf: [ :'Startup',:'Pequena e Média Empresa',:'Corporação',:'Centro de Pesquisa',:'Pesquisador Individual' ]
  enum tipodepessoappf: [:'Pessoa Física',:'Pessoa Jurídica']
  enum jparticipoudeoutrachamadadeprojetosdepdestartupsppf: [:'Sim, 1',:'Sim, 2',:'Sim, 3',:'Sim, mais de 5',:'Não']
  #enum current_phaseppf: [:'Entrada de Cadastros',:'Inbox - Startups',:'Administrativa',:'Técnica',:'Concluído']
#  enum current_phaseppf: [:'6989724',:'7794642',:'7794630',:'7794641',:'6989726']
#  enum leuasinformacoessobreasconcessionariasppf: [:'Sim','Não'] 
end

app/controllers/user_startups_controller.rb
class UserStartupsController < ApplicationController
  before_action :set_user_startup, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /user_startups
  # GET /user_startups.json

  def index
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin'
    @user_startups = UserStartup.all
   else
    redirect_to welcome_index_path
   end 
  end 
  # GET /user_startups/1
  # GET /user_startups/1.json
  def show
  end

  # GET /user_startups/new
  def new
    @user_startup = UserStartup.new
  end

  # GET /user_startups/1/edit
  def edit
  end

  # POST /user_startups
  # POST /user_startups.json
  def create
    @user_startup = UserStartup.new(user_startup_params)

    respond_to do |format|
      if @user_startup.save
        format.html { redirect_to @user_startup, notice: 'User startup was successfully created.' }
        format.json { render :show, status: :created, location: @user_startup }
      else
        format.html { render :new }
        format.json { render json: @user_startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_startups/1
  # PATCH/PUT /user_startups/1.json
  def update
    respond_to do |format|
      if @user_startup.update(user_startup_params)
        format.html { redirect_to @user_startup, notice: 'User startup was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_startup }
      else
        format.html { render :edit }
        format.json { render json: @user_startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_startups/1
  # DELETE /user_startups/1.json
  def destroy
    @user_startup.destroy
    respond_to do |format|
      format.html { redirect_to user_startups_url, notice: 'User startup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_startup
      @user_startup = UserStartup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_startup_params
      params.require(:user_startup).permit(:name, :status, :user_id)
    end
end

app/helpers/user_startups_helper.rb
module UserStartupsHelper
end

app/views/user_startups/_form.html.erb
<%= form_with(model: user_startup, local: true) do |form| %>
  <% if user_startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_startup.errors.count, "error") %> prohibited this user_startup from being saved:</h2>

      <ul>
      <% user_startup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_startups/edit.html.erb
<h1>Editing User Startup</h1>

<%= render 'form', user_startup: @user_startup %>

<%= link_to 'Show', @user_startup %> |
<%= link_to 'Back', user_startups_path %>

app/views/user_startups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Startups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_startups.each do |user_startup| %>
      <tr>
        <td><%= user_startup.name %></td>
        <td><%= user_startup.status %></td>
        <td><%= user_startup.user %></td>
        <td><%= link_to 'Show', user_startup %></td>
        <td><%= link_to 'Edit', edit_user_startup_path(user_startup) %></td>
        <td><%= link_to 'Destroy', user_startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Startup', new_user_startup_path %>

app/views/user_startups/new.html.erb
<h1>New User Startup</h1>

<%= render 'form', user_startup: @user_startup %>

<%= link_to 'Back', user_startups_path %>

app/views/user_startups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_startup.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user_startup.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_startup.user %>
</p>

<%= link_to 'Edit', edit_user_startup_path(@user_startup) %> |
<%= link_to 'Back', user_startups_path %>