config/routes.rb
Rails.application.routes.draw do
  
  

  resources :evaluations
  resources :sum_evaluations
  resources :projects
  #resources :cities
  #resources :states
  resources :user_startups
  resources :user_normals
  #resources :cargos
  resources :companypowers
  #resources :users
  get 'welcome/index'

 
  
=begin 

resources :user_normals do
match 'resetavaliacao' => 'user_normals#resetavaliacao', via: [:get, :post], as: :reset
#  collection {post :upload}
end  
=end 
devise_scope :users do
  get 'signin', to: 'users/sessions#new'
  #get 'signout', to: 'users/registration#destroy'
  get 'welcome/sobre', to: 'welcome#sobre', as: 'welcome/sobre' 
  get 'welcome/allpages', to: 'welcome#allpages', as: 'welcome/allpages'
  get 'users/accountaltsenha/:id', to: 'users#accountaltsenha', as: 'users/accountaltsenha'
  get 'user_normals/resetavaliacao/:id', to: 'user_normals#resetavaliacao', as: 'user_normals/resetavaliacao'  
end
  
  
resource :user, only: [:edit] do #Atenção rota para alterar a senha do usuário
  collection do
    patch 'update_password'
  end
end 

devise_for :users, controllers:{
  sessions: 'users/sessions'
 } 
  
resources :users  
root "welcome#index"  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
#If no route matches#
 match '*path', via: :all, to: redirect('/404')   
  
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:trackable,
         :recoverable, :rememberable, :validatable
         
  attr_accessor :liberar
  enum typeclasse: [ :'User_Normal',:'UserStartup']

  
  validates :email, uniqueness: {message: "já cadastrado" }
  validates_presence_of :email

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/
   #def new
     #super
   #end

def create
  teste=params[:user]
  retorno=validasenha(teste[:email],teste[:password])
  if (teste[:liberar]=='1')and(retorno=='ok')
   super
  else
    respond_to do |format|
      #format.js #views/users/create.js.erb
      if teste[:liberar]=='0'
       format.js { render "create" }
      elsif retorno!='ok'
       format.js { render "create1" }  
      end 
    end  
  end
end 
def validasenha(pemail,senha)
 if (pemail!='')and(senha!='') 
  teste=User.where(email:pemail)
  if teste!=[]
    if valid_password1?(senha,pemail)
      'ok'
    else
      "email/senha inválido" 
    end  
  else
    "email/senha inválido"
  end  
 else
   "email/senha inválido" 
 end   
end 

  def valid_password1?(password,pemail)
    @user=User.where(email:pemail)
    @user[0].valid_password?(password)
  end

 
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
=begin  
def validasenha(pemail,senha)
  teste=User.where(email:pemail)
  if teste!=nil
    if senha!=""    
      if teste[0].password==senha
        "ok"
      else
        "pass errada"  
      end
    else 
      "pass vazio"  
    end         
  else 
    "email inválido"  
  end    
end      
=end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy,:accountaltsenha]
  

  # GET /users
  # GET /users.json
  def index
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin'
    @q = User.ransack(params[:q].try(:merge, m: params[:combinator]))
     @users = @q.result.all.paginate(:page => params[:page], :per_page => 20).order(email: :asc)
   else
    redirect_to welcome_index_path
   end 
  end
  


  # GET /users/1
  # GET /users/1.json
  def show
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin' 
   else
    redirect_to welcome_index_path
   end      
  end

  # GET /users/new
  def new
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin'    
    @user = User.new
   else
    redirect_to welcome_index_path
   end     
  end

  # GET /users/1/edit
  def edit
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin'    
  
   else
    redirect_to welcome_index_path
   end     
  end
  
  def accountaltsenha
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin' 
     respond_to do |format|
      format.html { render :accountaltsenha }
     end
   else
     redirect_to welcome_index_path
   end   
  end  
  
def update_password
@user_normal=UserNormal.where(user_id:current_user.id)  
  if @user_normal[0].typerole=='admin'  
   if @user.update(password_params)  
    respond_to do |format|
      format.js
    end
   end
  else
    redirect_to welcome_index_path
  end 
end  






  # POST /users
  # POST /users.json
  def create
  @user_normal=UserNormal.where(user_id:current_user.id)  
  if @user_normal[0].typerole=='admin'     
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  else
   redirect_to welcome_index_path
  end     
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin'     
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
   else
    redirect_to welcome_index_path
   end     
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin'     
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
   else
    redirect_to welcome_index_path
   end     
  end

  private
    # Use callbacks to share common setup or constraints between actions.

   
    def set_user
     #if params[:id]!='sign_out'
       @user = User.find(params[:id])
     #end  
    end   
   
   
   
def gerasenharandom(len=32, character_set = ["A".."Z", "a".."z", "0".."9"])
  chars = character_set.map{|x| x.is_a?(Range) ? x.to_a : x }.flatten
  Array.new(len){ chars.sample }.join
end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:typeclasse,:password)
    end
def password_params
    params.require(:user).permit(:password)
end     
    
end

app/helpers/users_helper.rb
module UsersHelper
    
   


end

app/views/users/accountaltsenha.html.erb
<h2>Alteração de Senha</h2>
<%= yield :head %>
<%= form_with(model: @user, remote: true) do |f| %>
<div class="container is-widescreen">
<label class="label">DADOS GERAIS</label>    

</br>

  <label class="label"><%= f.label :email %></label>
  <div class ='form-control'>
   <%= f.text_field :email, :class => 'input' ,'required' => 'true','data-minlength'=>'3', 
   'data-error' => "Ops. Email inválido ou muito pequeno. " %>
  </div>
  </br> 

 
   <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  

 
<div class="field is-grouped">
  <p class="control">
    <%= f.button :'Atualizar Senha' , class: 'button is-primary'%>   
  </p>
  <p class="control">
    <a href="/users" class="button is-info">
      Cancel
    </a>
  </p>
</div>
  
  
  
  
  
  
  </div>
<% end %>

app/views/users/create.js.erb
var qtdErrors = <%= @user.errors.count%>
if (qtdErrors>0){
 $.notify("Ocorreu um erro!", "error");
}else {
 $.notify("Cadastrado com Sucesso!","sucess");
 document.getElementById('user_email').value="";
 }

app/views/users/edit.html.erb
<% content_for :head do %>
  <%=javascript_include_tag "notify" %>
<%end%>  

<%= form_with(model: @user, remote: true) do |f| %>
<div class="container is-widescreen">
<label class="label">DADOS GERAIS</label>    

</br>

  <label class="label"><%= f.label :email %></label>
  <div class ='form-control'>
   <%= f.text_field :email, :class => 'input' ,'required' => 'true','data-minlength'=>'3', 
   'data-error' => "Ops. Email inválido ou muito pequeno. " %>
  </div>
  </br> 
  <label class="label"><%=f.label :typeclasse%></label>
  <div class="form-control">
     <%= f.select(:typeclasse, User.typeclasses.keys.map {|typeclasse| [typeclasse.titleize,typeclasse]},{include_blank: false}, :class => 'form-control' )%>
    </br>
  </div> 
 </br> 
  
 
 
<div class="field is-grouped">
  <p class="control">
    <%= f.submit nil, :class => 'button is-primary' %>    
  </p>
  <p class="control">
    <a href="/users" class="button is-info">
      Cancel
    </a>
  </p>
</div>
  
  
  
  
  
  
  </div>
<% end %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<% if @user_normal[0].typerole=='admin' %>
  <%= link_to 'New User', new_user_path %>
<% end %>  


 <!-- Left side -->
  <div class="level-left">
 <p class="level-item">   
  <%= search_form_for @q do |f| %>  
    

  <%= f.label :email_cont %>
  <%= f.search_field :email_cont %>      
      
  <%= f.select :combinator, [['E','and'],['OU','or']] %>

  <%= f.label :typeclasse_eq %>
  <%= f.select :typeclasse_eq, User.typeclasses.to_a.map { |w| [w[0].humanize, w[1]] },{:include_blank=> "Selecione o tipo"} %> 
    
   

  <%= f.submit %>
  
<% end %>         
 </p>         
      
</div>


        Listagem de Usuários da plataforma.
         <% if User.count==1 %> 
          <class="text-muted m-b-30"><%=User.count%> registro
         <% else %> 
          <class="text-muted m-b-30"><%=User.count%> registros
         <% end %> 


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@q, :email) %></th>
      <th><%= sort_link(@q, :typeclasse) %></th>
      <th><%= sort_link(@q, :last_sign_in_at) %></th>   
      <th><%= sort_link(@q, :sign_in_count) %></th> 
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user_path(user), :class => '' %> </td>
        <td><%= user.typeclasse %></td>
        <% if user.last_sign_in_at!=nil%>
         <td><%=(user.last_sign_in_at).strftime("%d-%m-%Y %H:%M:%S") %></td>
        <% else %>
         <td> Não logou </td>
        <% end %>
        <td><%= user.sign_in_count %></td> 
      </tr>
    <% end %>
  </tbody>
</table




 <%= will_paginate @users %>   

app/views/users/new.html.erb
<% content_for :head do %>
  <%=javascript_include_tag "notify" %>
<%end%>  
<%= form_with(model: @user, remote: true) do |f| %>
<div class="container is-widescreen">
<label class="label">DADOS GERAIS</label>    

</br>

  <label class="label"><%= f.label :email %></label>
  <div class ='form-control'>
   <%= f.text_field :email, :class => 'input' ,'required' => 'true','data-minlength'=>'3', 
   'data-error' => "Ops. Email inválido ou muito pequeno. " %>
  </div>
  </br> 
  <label class="label"><%=f.label :typeclasse%></label>
  <div class="form-control">
     <%= f.select(:typeclasse, User.typeclasses.keys.map {|typeclasse| [typeclasse.titleize,typeclasse]},{include_blank: false}, :class => 'form-control' )%>
    </br>
  </div> 
 </br> 
   <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  
 
 
<div class="field is-grouped">
  <p class="control">
    <%= f.submit nil, :class => 'button is-primary' %>    
  </p>
  <p class="control">
    <a href="/users" class="button is-info">
      Cancel
    </a>
  </p>
</div>
  
  
  
  
  
  
  </div>
<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>  

  
  <dt><strong><%= model_class.human_attribute_name(:typeclasse) %>:</strong></dt>
  <dd><%= @user.typeclasse %></dd>  
  <dt><strong><%= model_class.human_attribute_name(:sign_in_count) %>:</strong></dt>
  <dd><%= @user.sign_in_count %></dd>   
  
  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<a href="/users/<%=@user.id%>/edit" class="button is-success">Alterar</a>
<a href="/users/accountaltsenha/<%=@user.id%>" class="button is-success">Alterar Senha</a> 
 

app/views/users/update.js.erb
var qtdErrors = <%= @user.errors.count%>
if (qtdErrors>0){
 $.notify("Ocorreu um erro!", "error");
}else {
 swal("User Salvo com Sucesso!", "Clique no botão!", "success")
   setTimeout(function(){
    window.location.replace("/users");
   },3000);
 }
 
 
 
 