config/routes.rb
Rails.application.routes.draw do
  
  

  resources :evaluations
  resources :sum_evaluations
  resources :projects
  #resources :cities
  #resources :states
  resources :user_startups
  resources :user_normals
  #resources :cargos
  resources :companypowers
  #resources :users
  get 'welcome/index'

 
  
=begin 

resources :user_normals do
match 'resetavaliacao' => 'user_normals#resetavaliacao', via: [:get, :post], as: :reset
#  collection {post :upload}
end  
=end 
devise_scope :users do
  get 'signin', to: 'users/sessions#new'
  #get 'signout', to: 'users/registration#destroy'
  get 'welcome/sobre', to: 'welcome#sobre', as: 'welcome/sobre' 
  get 'welcome/allpages', to: 'welcome#allpages', as: 'welcome/allpages'
  get 'users/accountaltsenha/:id', to: 'users#accountaltsenha', as: 'users/accountaltsenha'
  get 'user_normals/resetavaliacao/:id', to: 'user_normals#resetavaliacao', as: 'user_normals/resetavaliacao'  
end
  
  
resource :user, only: [:edit] do #Atenção rota para alterar a senha do usuário
  collection do
    patch 'update_password'
  end
end 

devise_for :users, controllers:{
  sessions: 'users/sessions'
 } 
  
resources :users  
root "welcome#index"  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
#If no route matches#
 match '*path', via: :all, to: redirect('/404')   
  
  

end

app/models/sum_evaluation.rb
class SumEvaluation < ApplicationRecord
    
 enum kind:[:'avalição1',:'avaliação2']
 enum questions1:[:'perg1',:'perg2']    
    
end

app/controllers/sum_evaluations_controller.rb
class SumEvaluationsController < ApplicationController
  before_action :set_sum_evaluation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sum_evaluations
  # GET /sum_evaluations.json
  def index
   @user_normal=UserNormal.where(user_id:current_user.id)  
   if @user_normal[0].typerole=='admin'
    @sum_evaluations = SumEvaluation.all
   else
    redirect_to welcome_index_path
   end 
  end 
  # GET /sum_evaluations/1
  # GET /sum_evaluations/1.json
  def show
  end

  # GET /sum_evaluations/new
  def new
    @sum_evaluation = SumEvaluation.new
  end

  # GET /sum_evaluations/1/edit
  def edit
  end

  # POST /sum_evaluations
  # POST /sum_evaluations.json
  def create
    @sum_evaluation = SumEvaluation.new(sum_evaluation_params)

    respond_to do |format|
      if @sum_evaluation.save
        format.html { redirect_to @sum_evaluation, notice: 'Sum evaluation was successfully created.' }
        format.json { render :show, status: :created, location: @sum_evaluation }
      else
        format.html { render :new }
        format.json { render json: @sum_evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sum_evaluations/1
  # PATCH/PUT /sum_evaluations/1.json
  def update
    respond_to do |format|
      if @sum_evaluation.update(sum_evaluation_params)
        format.html { redirect_to @sum_evaluation, notice: 'Sum evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @sum_evaluation }
      else
        format.html { render :edit }
        format.json { render json: @sum_evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sum_evaluations/1
  # DELETE /sum_evaluations/1.json
  def destroy
    @sum_evaluation.destroy
    respond_to do |format|
      format.html { redirect_to sum_evaluations_url, notice: 'Sum evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sum_evaluation
      @sum_evaluation = SumEvaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sum_evaluation_params
      params.require(:sum_evaluation).permit(:kind, :deadline)
    end
end

app/helpers/sum_evaluations_helper.rb
module SumEvaluationsHelper
end

app/views/sum_evaluations/_form.html.erb
<%= form_with(model: sum_evaluation, local: true) do |form| %>
  <% if sum_evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sum_evaluation.errors.count, "error") %> prohibited this sum_evaluation from being saved:</h2>

      <ul>
      <% sum_evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kind %>
    <%= form.number_field :kind %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.text_field :deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sum_evaluations/edit.html.erb
<h1>Editing Sum Evaluation</h1>

<%= render 'form', sum_evaluation: @sum_evaluation %>

<%= link_to 'Show', @sum_evaluation %> |
<%= link_to 'Back', sum_evaluations_path %>

app/views/sum_evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sum Evaluations</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sum_evaluations.each do |sum_evaluation| %>
      <tr>
        <td><%= sum_evaluation.kind %></td>
        <td><%= sum_evaluation.deadline %></td>
        <td><%= link_to 'Show', sum_evaluation %></td>
        <td><%= link_to 'Edit', edit_sum_evaluation_path(sum_evaluation) %></td>
        <td><%= link_to 'Destroy', sum_evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sum Evaluation', new_sum_evaluation_path %>

app/views/sum_evaluations/new.html.erb
<h1>New Sum Evaluation</h1>

<%= render 'form', sum_evaluation: @sum_evaluation %>

<%= link_to 'Back', sum_evaluations_path %>

app/views/sum_evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @sum_evaluation.kind %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @sum_evaluation.deadline %>
</p>

<%= link_to 'Edit', edit_sum_evaluation_path(@sum_evaluation) %> |
<%= link_to 'Back', sum_evaluations_path %>